### ISSUE TITLE
组件测试任务

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs-Awesome/fc-alibaba-component#34]
组件测试任务详细说明：本次测试组件是全流程的测试，主要包括但不限于函数创建、移除、Auto能力以及调试等能力。

- 流程1: 
    - 测试1: init 一个 event 函数 / http 函数 进行 部署
    - 测试2: 在测试1基础上，增加VPC，Logs等日志能力进行部署测试
    - 测试3: 在测试2的基础上，将项目发布出去（版本+别名）
    - 测试4: 在3的基础上，进行log查看
    - 测试5: 部署一个Golang项目（通过extends进行build等操作）
    - 测试6: 移除上面项目

- 流程2:
    - 每个触发器的函数都创建一个，每个触发器参数都走一次流程
    - 移除上面项目

- 流程3:
    - 部署一个超大规模的项目，例如300M的项目，通过镜像形式部署
    - 将上面的项目不用镜像模式部署，直接走NAS
    - 移除上面项目

- 流程4:
    - 将项目https://www.serverlesschina.com/post/42.html部署到阿里云函数计算上
    - 移除上面项目

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/96222311-9c92c780-0fbe-11eb-9ff5-6f3e71d83086.png)
密钥打印的时候是否需要隐藏中间部分呢？

**Comment by anycodes** [comment]
> ![image](https://user-images.githubusercontent.com/56686088/96222311-9c92c780-0fbe-11eb-9ff5-6f3e71d83086.png)
> 密钥打印的时候是否需要隐藏中间部分呢？

只有在add的时候会显示，其余的时候，都不会显示完整的。

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/96236682-ec798a80-0fce-11eb-9b86-a256140fb32e.png)
deploy servce 没有打印

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/96411881-c7c62280-121b-11eb-95d4-e773dd949473.png)
部署一个java8项目（通过extends进行build等操作）

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/96416528-b6344900-1222-11eb-8c18-046a8ab64598.png)
Log 和 timer 触发器的 开关不生效

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/96423315-be44b680-122b-11eb-9de7-21b04893060c.png)

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/96430217-79714d80-1234-11eb-977d-a38a8c0160c0.png)

![image](https://user-images.githubusercontent.com/56686088/96430257-842be280-1234-11eb-848a-0b1413485d36.png)
runtime：nodejs
环境变量总会新增两个字段，其中一个为 undefind

**Comment by wss-git** [comment]
> ![image](https://user-images.githubusercontent.com/56686088/96236682-ec798a80-0fce-11eb-9b86-a256140fb32e.png)
> deploy servce 没有打印

已修复

**Comment by wss-git** [comment]
> ![image](https://user-images.githubusercontent.com/56686088/96416528-b6344900-1222-11eb-8c18-046a8ab64598.png)
> Log 和 timer 触发器的 开关不生效

已修复
