### ISSUE TITLE
sync 同步回来的Access问题

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs-Awesome/fc-alibaba-component#59]
同步回来的Yaml中增加了AccessAlias，实际项目中应该是Access，另外如果用户原先的yaml没有这个key，不要加，否则s工具可能会错误解析。

**Comment by wss-git** [comment]
这个 AccessAlias 是 s-core 给解析出来的字段，之前没有处理， 现在在 https://github.com/Serverless-Devs-Awesome/fc-sync-alibaba-component/blob/main/index.js#L95-L98 新仓库里面修复了

**Comment by anycodes** [comment]
感谢大佬。
