### ISSUE TITLE
s remove functions 未报错

### ISSUE THREAD

**Issue by git-qfzhang** [Serverless-Devs-Awesome/fc-alibaba-component#71]
删除函数的指令为  s remove function，但是当我指令打印成 s remove functions 时，并不会报错，却显示正常执行，如下图所示：

![image](https://user-images.githubusercontent.com/52195264/99631173-17477a80-2a76-11eb-9c5e-a976b02059ac.png)

我的 yaml 文件内容为：

![image](https://user-images.githubusercontent.com/52195264/99631217-29291d80-2a76-11eb-81cb-1251a3f0e327.png)

**Comment by anycodes** [comment]
已经处理
